### ISSUE TITLE
Screen ratio and mobile support

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#13]
1. [x] layout should display in 16:9 aspect ratio.
2. [x] Layout should take the entire screen, without margins, in any 16:9 device (resizing according to size)
3. [x] In a screen that is not 16:9, black margins will be shown in the remaining space in one dimension (height or width)
4. [x] Test if this works also in mobile devices (landscape). the entire stage should resize to fit the screen

**Comment by LiadOwar** [comment]
deadline: 29.4 hopefully sooner 
most of this issue is done, I may need help with the margins.

**Comment by mtr574** [comment]
Done with this one
