### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#15]
1. replace to other BG image
2. add missing life line BG (blue half circle)
3. add two missing links in top

**Comment by HelmetRemover** [comment]
link to survival guide:
http://midburn.org/he-survival-guide/

@omerpines which FB group/page of Midburn should the game link to?

**Comment by LiadOwar** [comment]
All I need the facebook link and this part is done. (without cellphone modifications)

**Comment by HelmetRemover** [comment]
@omerpines which FB group/page of Midburn should the game link to?

**Comment by omerpines** [comment]
https://www.facebook.com/midburns
