### ISSUE TITLE
Add question streak indicator

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#16]
1. place according to design (logical order like reading direction, RTL)
2. they have three states: 
- not achieved - dark
- achieved - lit (solid)
- in progress - lit (blinking slowly)
3. prepare for two other layouts - streak of 3, streak of 4 (this will be set by server)

**Comment by LiadOwar** [comment]
done! the current design supports as many streaks as we wont (it my couse UI problems after to many streak nums but for 3 -4 no problem (its a variable)
