### ISSUE TITLE
Correct View flow

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#17]
First remove the first view
then the flow is:
2. load the game main view with or without first question
3. appears the instructions pop up with its "play" button (user hit's "play")
4. pop up goes away and main game flow starts
5. at "game won" state, win popup appears (**and makes API call**)
6. it displays two buttons ("replay" and "go to tickets")
7. user clicks "replay" ---> execute replay flow (start from top with all resources reset)
8. user clicks "go to tickets" ---> redirect to ticket link

**Comment by HelmetRemover** [comment]
@omerpines Please provide here the proper link to direct back to tickets after game ended

**Comment by LiadOwar** [comment]
I belive this will be done at worst case 22.4 hopefully sooner

**Comment by omerpines** [comment]
The link back is sent with the  API call to the system's backend.
If user decides to leave game without completing the game, return to
https://profile.midburn.org

On 18 Apr 2017 1:23 am, "LiadOwar" <notifications@github.com> wrote:

I belive this will be done at worst case 22.4 hopefully sooner

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Midburn/Midburn-Quiz-Frontend/issues/17#issuecomment-294609483>,
or mute the thread

**Comment by HelmetRemover** [comment]
@omerpines 
Does it need to return some user identification?

**Comment by HelmetRemover** [comment]
@omerpines This is not the flow we agreed on, in the meeting with Tom.
Please read description again. that's the flow we are preparing to.

Aside of the description above (n8), there is no option to "leave the game" (closing the tab, maybe)

**Comment by omerpines** [comment]
OK. No return button.

**Comment by omerpines** [comment]
Need identification for API call. Not for returning to profile.midburn.org

**Comment by HelmetRemover** [comment]
OK, can you make a more detailed specification in #19 ?
Or ask Tom to do it?
How does the game recieve identification from ticket system and how does it return it?

**Comment by omerpines** [comment]
I can't since I don't know how the API parameters will be.
Please ask Tom to do it in JIRA.

**Comment by HelmetRemover** [comment]
This doesn't work (redirects to ynet):
user clicks "go to tickets" (at win popup) ---> redirect to tickets. 
API call should have already been made.

**Comment by eladg** [comment]
The following will happen now:

If uid was given (on the URL), we will redirect to:
```
https://profile.midburn.org/he/user/<< Game's user id >>/tickets
```
This doesn't guarantee access to the page, as we have no control over it. Yet, if no one will mess around with the params, everything should works fine.

If no UID was given (playing the game without being connected), pressing the "Go To Tickets" button will redirect to the profiles system (i.e. `https://profile-test.midburn.org/he`)

**Comment by HelmetRemover** [comment]
@eladg 
Is this tested by you?
If not confirmed, please leave open with label "test"
