### ISSUE TITLE
reset topic progress if question cycle resets

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#18]
if user played 6 questions and didn't pass, his question cycle restarts.
in this case, refill lifelines, if they were used, and reset correct question streak.

**Comment by HelmetRemover** [comment]
Lifelines are not refilled when category is reset (start category again)

**Comment by HelmetRemover** [comment]
Linfelines are not reset also when starting a new category

**Comment by mtr574** [comment]
@HelmetRemover works for me.
on which device do you have this issue?

**Comment by mtr574** [comment]
@LiadOwar fixed it. done
