### ISSUE TITLE
API Call to change "won game" in drupal

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#19]
Tom meir will develop this api, frontend code needs to execute the call when "win popup" appears.

**Comment by HelmetRemover** [comment]
api call to tell drupal to update user NNNN who completed the games:
**first step:** 
login using the api:

```
var request = require("request");

var options = { method: 'POST',
  url: 'https://profile-test.midburn.org/en/api/user/login',
  headers: 
   { 
     'cache-control': 'no-cache',
     'content-type': 'application/x-www-form-urlencoded' },
  form: { username: 'omerpines@hotmail.com', password: '123456' } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

the result should include a property called sessid. 
you MUST copy this and use the value you got in all future calls as the header property x-csrf-token. otherwise system will not remember you as logged in. 
if you do not know your current sessid and wish to recieve without loggin in you can GET https://profile-test.midburn.org/en/services/session/token and recieve that string

**final step -** 
call the action of passing: this will return true on success or a string with the description of the failure.

```
var request = require("request");

var options = { method: 'POST',
  url: 'https://profile-test.midburn.org/en/api/games/NNNN/pass',
  headers: 
   { 
     'cache-control': 'no-cache',
     'content-type': 'application/x-www-form-urlencoded',
     'x-csrf-token': 'xu2W7fdyklKONDpDc3r_q__TOKENEXAMPLE_____drpduWyOA' },
  form: {} };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});

```

**Comment by HelmetRemover** [comment]
@LiadOwar all yours! :)

**Comment by omerpines** [comment]
@LiadOwar , please use the following credentials to test if the API is working properly:

UID (to use in the API): 4971
Environment: https://profile-test.midburn.org 
Email: sir_ruvzi@hotmail.com
Password: WholeNew1 (don't worry, it's just a test user with no permissions)

After running the API call, go to the environment and login with the user.
After logging in, click on "My tickets" in the menu and click on "Download and Print ticket" option.

If everything goes smoothly with the API call, you should get a print of the ticket.
If the API call did not change the "User passed game" checkbox, you will jump to games.midburn.org to play the game.

Let me know if you need any further assistance.

**Comment by mtr574** [comment]
#30 is merged and code should be tested by QA team.
