### ISSUE TITLE
Display image over game if rotated to portrait in mobile

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#21]
1. [x] run constantly code that identifies portrait aspect ratio
2. [x] display image that blocks view and suggests to turn deice to landscape
3. [x] remove this image when device turned

**Comment by HelmetRemover** [comment]
@mtr574 
As discussed, please make sure this runs constantly or at least on any orientation change as well as on launch.

**Comment by mtr574** [comment]
This one is done. has black screen with a notice to end-user

**Comment by eladg** [comment]
Reopened after it was recreated

**Comment by mtr574** [comment]
@media (orientation: portrait) {
    div#change-viewport-alert {
        display: block !important;
    }
}

**Comment by mtr574** [comment]
@HelmetRemover check and close

**Comment by HelmetRemover** [comment]
@LiadOwar 
Can you test on Android?
