### ISSUE TITLE
Pop-Up implementation

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#25]
1. See issue #17 for buttons and flow
2. use bootstrap to create vector design for popups, like in answers
3. Use a "static text field" we can change in frontend if needed (not an image)
4. Keep a part of it Dynamic (the word for 2-3-4 streak), to be determined by same param as game logic

**Comment by eladg** [comment]
The current issue:
- No error handling for failed new game.

(Nate: the issue recreates every time the Heroku dyno is asleep)

**Comment by mtr574** [comment]
Heroku dyno set to hobby => redirect API calls to production end-point

**Comment by mtr574** [comment]
@HelmetRemover check and close

**Comment by HelmetRemover** [comment]
@mtr574 
Not sure what's the expected result here.

Is this supposed to show an error when new game isn't created?

**Comment by mtr574** [comment]
@HelmetRemover if by any case the game failed to start, cause of response failure (from API) then alert pops-up (saying 'please refresh'...) + hiding main container, so you dont see the game UI.

**Comment by HelmetRemover** [comment]
@mtr574 sweeet, so I guess I cannot test this?
You are hereby authorized to test and close issue if confirmed.
