### ISSUE TITLE
Basic Google Analytics

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#29]
1. Basic implementation:
- add simple reporting code from Google analytics to track number of users and time on site

2. Advanced Implementation; track events:
- Win popup
- Topic restart (Question cycle ended)
- lifeline 1 used
- lifeline 2 used

**Comment by HelmetRemover** [comment]
@omerpines 
Is there a Google analytics account we should use?

**Comment by omerpines** [comment]
Yes, Midburn's.
Sending all details via slack.

**Comment by HelmetRemover** [comment]
Google analytics script:
```
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-47499017-6', 'auto');
  ga('send', 'pageview');
```

As you can see, the UA tracking is : UA-47499017-6

**Comment by mtr574** [comment]
Taking it.

**Comment by mtr574** [comment]
`/js/ga.js` is a file including the Google analytics init script and a function called: `ga_notify`
which takes `eventCategory, eventAction, eventLabel` as arguments.

Call this func where-ever we want to notify Google analytics on an event.

**Comment by HelmetRemover** [comment]
Sorry @mtr574, is the basic reporting implemented? (1)
So we need to call only specific events now? (2)
