### ISSUE TITLE
Display shifts down when browser web address line is displayed

### ISSUE THREAD

**Issue by LiadOwar** [Midburn/Midburn-Quiz-Frontend#36]
![screenshot_20170425-231711](https://cloud.githubusercontent.com/assets/27013733/25406558/c3aa24dc-2a0f-11e7-94ff-89d1b6eeae00.png)
![screenshot_20170425-231656](https://cloud.githubusercontent.com/assets/27013733/25406588/db8a32a4-2a0f-11e7-90d1-6192290fb855.png)

**Comment by HelmetRemover** [comment]
Suggested solution (for chrome) - create some extra margin at top, and auto-scroll until it is above the screen (this will get rid of of the URL bar in chrome)

**Comment by mtr574** [comment]
i see this code is implemented 
```
                // hide address bar
                if (document.documentElement.scrollHeight < window.outerHeight / window.devicePixelRatio)
                    document.documentElement.style.height = (window.outerHeight / window.devicePixelRatio) +
                    'px';
                setTimeout(window.scrollTo(1, 1), 0);
```

need to test on real devices.
