### ISSUE TITLE
Drupal API call creates errors

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#44]

**Comment by eladg** [comment]
Still no signin solution from Drupal + No real idea what the profiles system response with `/services/session/token` for unsigned user. Would have been great to receive an error msg of some sort but the current response is token for every request... which makes in impossible to distinguish between a signed user and an unsigned user.

**Comment by eladg** [comment]
In the meantime, removed login code and showing an error alert.

Will make sure the login session will last at least for 12 hours to prevent an expired game to be played.

**Comment by mtr574** [comment]
i got this

**Comment by mtr574** [comment]
irelevant.
