### ISSUE TITLE
New CSV (Q&A) and Hebrew category names

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#46]
1. Create a proper CSV from XLSX (attached).
2. change category names to hebrew (see comments)
3. make sure categories appear in this order

**Comment by HelmetRemover** [comment]
[Burner-games-2017-DB.xlsx](https://github.com/Midburn/Midburn-Quiz-Frontend/files/984504/Burner-games-2017-DB.xlsx)

**Comment by HelmetRemover** [comment]
These are the category names in Hebrew.
Categories must appear in this order. Q&A in CSV are according to this mapping to numbers:
categories_keys = {
      "1" => Category.find_by_name("מדריך ההישרדות"),
      "2" => Category.find_by_name("עשרת העקרונות"),
      "3" => Category.find_by_name("גופים והתמצאות באירוע"),
      "4" => Category.find_by_name("חשל"ש"),
      "5" => Category.find_by_name("גבולות אישיים"),
    }

**Comment by eladg** [comment]
I can't distinguish between the old and the new questions... would appreciate the help testing this

**Comment by HelmetRemover** [comment]
@eladg 
Looks like total # of questions is good (70), and I went through several, seem like the new ones.
Please note the order of topics - should NOT be random, but according to the order specified in this issue.

**Comment by eladg** [comment]
OK, will fix the randomness on the backend. This ticket can be closed now.

**Comment by HelmetRemover** [comment]
@eladg 
please re-open and label "test" anything I should test, this issue included

**Comment by eladg** [comment]
The ticket is on a different repo. Also, I've already did it, but had to rollback before my implementation as Liad was not handling the backend with all questions method.

I'm testing myself, which is quicker... :)
