### ISSUE TITLE
replace popup text

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#49]
Greeting popup:
- [x] משחקי הברן
- [x] ברוכים הבאים למשחק הטריוויה החדש שמשגע את הפלאייה! רוצים כרטיסים? אתם חייבים לעבור אותו!
איך מנצחים? עליכם לעבור 5 נושאים שקשורים למידברן, ובכל נושא לענות נכון על [STREAK_NUMBER] שאלות רצופות. לרשותכם שני גלגלי הצלה לכל נושא. בהצלחה!

Win popup:
- [x] כל הכבוד! ניצחתם את משחקי הברן. נתראה בקרוב!

- [x] כפתור: קדימה אל הכרטיסים! - its image bg
- [x] כפתור: התמכרתי! לשחק שוב - its image bg

**Comment by mtr574** [comment]
done

**Comment by HelmetRemover** [comment]
@mtr574 לא נראה ככה
![image](https://cloud.githubusercontent.com/assets/4154401/25846394/51f6eab8-34ba-11e7-8353-f9a818ffae7f.png)

**Comment by HelmetRemover** [comment]
@mtr574 
Here?
https://s3-eu-west-1.amazonaws.com/games.midburn.org/index.html
doesn't seem so.
Games.midburn.org is not reachable.

**Comment by mtr574** [comment]
@HelmetRemover done.
