### ISSUE TITLE
burner-games- production server

### ISSUE THREAD

**Issue by mtr574** [Midburn/Midburn-Quiz-Frontend#50]
`burner-games.herokuapp.com/api/v1` should behave like `burner-games-staging.herokuapp.com/api/v1`

reproduce:
1. in `config.json` set api_url to burner-games.herokuapp.com/api/v1
2. start the game (this api call works)
3. new_question call - get error
```
Request URL:https://burner-games.herokuapp.com/api/v1/games/GlEozO/new_question/
Request Method:POST
Status Code:404 Not Found
Remote Address:54.228.236.47:443
```

**Comment by HelmetRemover** [comment]
@eladg 
I suggest dropping this task. we look great on staging
