### ISSUE TITLE
Drupal notify on Win the game should be on backend

### ISSUE THREAD

**Issue by mtr574** [Midburn/Midburn-Quiz-Frontend#54]
# Drupals  #end-points when passing the quiz
## We have 2 end-points provided from the Drupal team

1. (POST) Login as a master user, returns a session id (sessid).
``https://profile.midburn.org/en/api/user/login``

_Master user_
user: spark@midburn.org
password: ********

```
headers: 
  { 
     'cache-control': 'no-cache',
     'content-type': 'application/x-www-form-urlencoded' },
  form: { username: 'spark@midburn.org',
      password: 'spark'
  }
}
```

if you do not know your current sessid and wish to recieve without loggin in (again)
you can GET `https://profile.midburn.org/en/services/session/token`

2. (POST) notifying Drupal about winning, include session id with this request.
``https://profile.midburn.org/en/api/games/[USER_ID]/pass``

```
  headers: 
   { 
     'cache-control': 'no-cache',
     'content-type': 'application/x-www-form-urlencoded',
     'x-csrf-token': 'xu2W7fdyklKONDpDc3r_q__TOKENEXAMPLE_____drpduWyOA' 
}
```

**Comment by mtr574** [comment]
original issue: https://github.com/Midburn/Midburn-Quiz-Frontend/issues/19

**Comment by HelmetRemover** [comment]
@mtr574 
This should be closed, correct?

**Comment by mtr574** [comment]
this is done
