### ISSUE TITLE
goToTicketBtn url should be...

### ISSUE THREAD

**Issue by mtr574** [Midburn/Midburn-Quiz-Frontend#57]
When the game ends, a popup shows two buttons, one of them leads to tickets page in Drupalz

Verify if this is the current URL: `https://profile.midburn.org/he/user/[USER_ID]/tickets`

**Comment by HelmetRemover** [comment]
@mtr574 
We've tested the full flow. winning the game activates "won game" on drupal.
Please close this if satisfied
